version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_app_development
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: task_app_development

volumes:
  db-data: